const KEY="nv_chat_state_v1";
const base=document.getElementById("apiBase"), key=document.getElementById("apiKey");
const temperature=document.getElementById("temperature"), maxTokens=document.getElementById("maxTokens");
base.value=localStorage.getItem("nv_api_base")||"";
key.value=localStorage.getItem("nv_api_key")||"";
temperature.value=localStorage.getItem("nv_temperature")||"0.7";
maxTokens.value=localStorage.getItem("nv_max_tokens")||"256";
const state=JSON.parse(localStorage.getItem(KEY)||"null")||{active:null,chats:[]};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function download(name,text,type="application/json"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportChats(){download("notvisibleai-chats.json",JSON.stringify(state,null,2))}
function importChats(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x||!Array.isArray(x.chats))throw new Error("Invalid chat export");state.chats=x.chats;state.active=x.active||state.chats[0]?.id||null;save();render()}catch(e){alert(e.message)}};r.readAsText(file)}

const current=()=>state.chats.find(x=>x.id===state.active);
function newChat(){const c={id:crypto.randomUUID(),title:"New conversation",messages:[]};state.chats.unshift(c);state.active=c.id;save();render()}
function ensure(){if(!current())newChat()}
function render(){ensure();const c=current(),box=document.getElementById("messages");document.getElementById("chatTitle").textContent=c.title;box.innerHTML=c.messages.length?"":"<div class='msg bot'>Hello — I’m NV-0.2. Ask me something.</div>";c.messages.forEach(m=>{const e=document.createElement("div");e.className="msg "+(m.role==="user"?"user":"bot");e.textContent=m.content;box.appendChild(e)});box.scrollTop=box.scrollHeight;const h=document.getElementById("history");h.innerHTML="";state.chats.slice(0,20).forEach(x=>{const b=document.createElement("button");b.className="history-item"+(x.id===state.active?" active":"");b.textContent=x.title;b.onclick=()=>{state.active=x.id;save();render()};h.appendChild(b)})}
function api(){return base.value.trim().replace(/\/$/,"")}
async function health(){const s=document.getElementById("status"),d=document.getElementById("dot");if(!api()){s.textContent="Local chat history · connect an API to send";return}try{const r=await fetch(api()+"/health");if(!r.ok)throw 0;const x=await r.json();s.textContent=x.inference_attached?"API online · inference attached":"API online · inference not attached";d.className="on"}catch(e){s.textContent="API unavailable";d.className="off"}}
document.getElementById("saveSettings").onclick=()=>{localStorage.setItem("nv_api_base",base.value.trim());localStorage.setItem("nv_api_key",key.value);localStorage.setItem("nv_temperature",temperature.value);localStorage.setItem("nv_max_tokens",maxTokens.value);health()};
document.getElementById("newChat").onclick=newChat;
document.getElementById("renameChat").onclick=()=>{const c=current(),n=prompt("Conversation name:",c.title);if(n&&n.trim()){c.title=n.trim();save();render()}};
document.getElementById("exportChats").onclick=exportChats;document.getElementById("importInput").onchange=e=>{if(e.target.files[0])importChats(e.target.files[0])};
document.getElementById("clearChats").onclick=()=>{if(confirm("Clear all local chat history?")){state.chats=[];state.active=null;save();render()}};
document.getElementById("fileInput").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{let t="";if(/\.(txt|md|json|csv|py|js|ts|html|css)$/i.test(f.name)){t=await f.text()}else{if(!api()){throw new Error("Connect the API before attaching PDF, DOCX, or XLSX files.")}const form=new FormData();form.append("file",f);const r=await fetch(api()+"/v1/files/extract",{method:"POST",headers:key.value?{Authorization:"Bearer "+key.value}:{},body:form});const d=await r.json();if(!r.ok)throw new Error(d.detail||"File extraction failed");t=d.text||""}window.nvAttachment={name:f.name,text:t.slice(0,100000)};document.getElementById("attachment").textContent=f.name+" attached ("+t.length+" extracted characters)"}catch(err){alert(err.message)}};
document.getElementById("copyLast").onclick=async()=>{const c=current();const m=[...c.messages].reverse().find(x=>x.role==="assistant");if(m&&navigator.clipboard){await navigator.clipboard.writeText(m.content);document.getElementById("copyLast").textContent="Copied";setTimeout(()=>document.getElementById("copyLast").textContent="Copy last",1200)}};
document.getElementById("chatForm").onsubmit=async e=>{e.preventDefault();ensure();const input=document.getElementById("prompt"),text=input.value.trim();if(!text)return;const c=current();let content=text;if(window.nvAttachment)content+="\n\n[Attached file: "+window.nvAttachment.name+"]\n"+window.nvAttachment.text;c.messages.push({role:"user",content});input.value="";window.nvAttachment=null;document.getElementById("attachment").textContent="";if(c.title==="New conversation")c.title=text.slice(0,42);save();render();if(!api()){c.messages.push({role:"assistant",content:"Connect a running NOTVISIBLEAI API using the connection settings to receive a model response."});save();render();return}try{const r=await fetch(api()+"/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",...(key.value?{Authorization:"Bearer "+key.value}:{})},body:JSON.stringify({model:"nv-0.2",messages:c.messages,temperature:Number(temperature.value),max_tokens:Number(maxTokens.value)})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Request failed");c.messages.push({role:"assistant",content:d.choices?.[0]?.message?.content||"No response"});save();render()}catch(err){c.messages.push({role:"assistant",content:"Request error: "+err.message});save();render()}};
render();health();
document.getElementById("regenerate").onclick=async()=>{const c=current();const i=c.messages.map(x=>x.role).lastIndexOf("user");if(i<0)return;c.messages=c.messages.slice(0,i+1);save();render();if(!api())return;try{const r=await fetch(api()+"/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",...(key.value?{Authorization:"Bearer "+key.value}:{})},body:JSON.stringify({model:"nv-0.2",messages:c.messages,temperature:Number(temperature.value),max_tokens:Number(maxTokens.value)})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Request failed");c.messages.push({role:"assistant",content:d.choices?.[0]?.message?.content||"No response"});save();render()}catch(err){c.messages.push({role:"assistant",content:"Request error: "+err.message});save();render()}};